### ISSUE TITLE
Plugin not working correct

### ISSUE THREAD

**Issue by stefanwendelmann** [codeclou/maven-releaseinfo-macro#8]
Confluence Server 6.10.0

Test works fine
https://codeclou.io/test-maven-releaseinfo-macro/v1.6/public/example-release/1.5/pom.xml

Own pom.xml giving me empty result 

![image](https://user-images.githubusercontent.com/3920790/45349191-ef644e80-b5b0-11e8-834a-9bfa7fd91368.png)

Is this only for Parent / Master Pom ?

Thanks in advance!

**Comment by clouless** [comment]
Hi,

As the userguide states this plugin is only for pom.xml files that are used for software delivery.
The format is described in: https://codeclou.io/maven-releaseinfo-macro/1.8.0/user-guide/#right-format

You can download a sample parent and module pom from the userguide.

So it works as expected.
